directory: ~/Music/beets-library #music folder directory
library: ~/Dropbox/beets/library.db #default location for library

ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

import:
  write: yes #metadata tags are written to files
  copy: yes #copy files into the library
  move: no
  resume: ask
  incremental: no
  log: ~/Music/import.log


asciify_paths: yes #alle Paths in ascii machen
threaded: yes
original_date: yes #tagge Alben mit dem originalen Erscheinungsdatum 
per_disc_numbering: yes

paths:
  default: $albumartist/$album%aunique{}/$disc-$track $title
  comp: Compilation/$album%aunique{}/$disc-$track $title
  singleton: Non-Album/$artist/$title
  albumtype:soundtrack: Soundtracks/$album/$disc-$track $title


plugins: fromfilename embedart fetchart mpdupdate

embedart:
  ifempty: yes

mpdupdate:
  host: localhost
  port: 6600

